#!/bin/bash
# GrokiPedia Security Auditor - Proposal Generator

INPUT_FILE="${1:-client-urls.txt}"

if [[ ! -f "$INPUT_FILE" ]]; then
    echo "Error: Input file $INPUT_FILE not found"
    echo "Create a file with one URL per line"
    exit 1
fi

mkdir -p proposals

echo "Generating proposals for clients in $INPUT_FILE..."

while IFS= read -r url; do
    [[ -z "$url" ]] && continue
    [[ "$url" =~ ^# ]] && continue
    
    client_name=$(echo "$url" | sed -e 's|^[^/]*//||' -e 's|/.*||' -e 's|www.||')
    proposal_file="proposals/${client_name}_proposal.txt"
    
    cat > "$proposal_file" << EOL
Dear ${client_name} Team,

We've completed a comprehensive security audit of your website (${url}) using our advanced GrokiPedia Security Auditor.

EXECUTIVE SUMMARY:
Our automated security analysis has identified several areas where your website's security can be significantly improved.

KEY FINDINGS:
- SSL/TLS Configuration: [DETAILED ANALYSIS]
- Security Headers: [COMPREHENSIVE REVIEW]
- Dependency Vulnerabilities: [THIRD-PARTY RISK ASSESSMENT]
- Common Security Issues: [MISCONFIGURATION ANALYSIS]

RECOMMENDATIONS:
1. Implement missing security headers
2. Update vulnerable dependencies
3. Strengthen SSL/TLS configuration
4. Regular security monitoring

PRICING:
Our comprehensive security audit and remediation services are available for a one-time fee of \$297, or as part of our ongoing monitoring service at \$97/month.

NEXT STEPS:
1. Review the detailed security report
2. Schedule a consultation call
3. Implement recommended security improvements

Best regards,
GrokiPedia Security Team

---
Generated by GrokiPedia Security Auditor v2.3.1-solidity
EOL

    echo "Generated proposal: $proposal_file"
done < "$INPUT_FILE"

echo "✅ All proposals generated successfully!"
